language: none
build:
  ci:
    - echo "Hello, World!"
    - The secret is - echo $(shipctl get_integration_resource_field aws_dummy_res secretKey)
    
integrations:
  generic:
    - integrationName: aws_dummy
    
resources:
  - name: aws_dummy_res
    type: integration
    integration: aws_dummy

jobs:
  - name: test_subint_ci_runCI
    type: runCI
    steps:
      - IN: aws_dummy_res
