language: none
build:
  ci:
    - echo "Hello, World!"
integrations:
  generic:
    - integrationName: aws_dummy

jobs:
  - name: test_subint_ci_runCI
    type: runCI
    steps:
      - IN: aws_dummy
